Hid unused menu items, added german for searchbox
OpusCapita/react-components pull request #6
Opened 2017-06-27 14:13 UTC by mayank-cronj

implements OpusCapita/bnp#103

2017-06-27 14:16 UTC, patrykkopycinski requested changes

2017-06-27 14:16 UTC, patrykkopycinski commented on src/SidebarMenu/SidebarMenu.js
> +              <img src="" style={{ height: '1.4em' }} />
hmm? how it's going to work without `src`?

2017-06-27 14:23 UTC, mayank-cronj commented on src/SidebarMenu/SidebarMenu.js
> +              <img src="" style={{ height: '1.4em' }} />
My bad. Had removed while testing. Fixed in new commit

2017-06-27 14:28 UTC, patrykkopycinski requested changes

2017-06-27 14:28 UTC, patrykkopycinski commented on src/HeaderMenu/i18n/de.js
> +  	search: 'Suche',
wrong indentation

2017-06-27 14:49 UTC, mayank-cronj commented on src/HeaderMenu/i18n/de.js
> +  	search: 'Suche',
Followed the same indentation from the other translation files. Could you tell me what needs to be changed?

2017-06-29 06:42 UTC, gr4per approved these changes
lgtm
we never set strict formatting rules, but
1. no tabs
2. 2 spaces per indent
3. don't change formatting in code files when not doing semantical changes, this is to keep diffs small

That being said, this is ok for now, today no time to argue about indents

2017-06-29 06:55 UTC, merged